spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.6:3310/oil?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: newos_user
    password: Newos@2025
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  data:
    redis:
      host: newos-redis.newos
      port: 6379
      password: GWVjCiZnbJDbHRsN
      database: 2
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 20
          min-idle: 5
          max-wait: -1ms

  rabbitmq:
    host: newos-rabbitmq-0-service.newos
    port: 5672
    username: weicheche
    password: weicheche20241224
    virtual-host: /prod
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos:8848
#        username: ${NACOS_USERNAME:nacos}
#        password: ${NACOS_PASSWORD:nacos}
#        namespace: prod
#        group: DEFAULT_GROUP
#        heart-beat-interval: 30000
#        heart-beat-timeout: 180000
#        ip-delete-timeout: 30000
#      config:
#        server-addr: nacos:8848
#        username: ${NACOS_USERNAME:nacos}
#        password: ${NACOS_PASSWORD:nacos}
#        namespace: prod
#        group: DEFAULT_GROUP
#        file-extension: yml
#        import-check:
#          enabled: false
#    sentinel:
#      transport:
#        dashboard: sentinel:8080
#        port: 8719
#      enabled: true
#      datasource:
#        ds1:
#          nacos:
#            server-addr: nacos:8848
#            username: ${NACOS_USERNAME:nacos}
#            password: ${NACOS_PASSWORD:nacos}
#            dataId: ${spring.application.name}-sentinel
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: prod_tx_group
#  config:
#    type: nacos
#    nacos:
#      server-addr: nacos:8848
#      username: ${NACOS_USERNAME:nacos}
#      password: ${NACOS_PASSWORD:nacos}
#      group: SEATA_GROUP
#      namespace: prod
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: nacos:8848
#      username: ${NACOS_USERNAME:nacos}
#      password: ${NACOS_PASSWORD:nacos}
#      group: SEATA_GROUP
#      namespace: prod

#xxl:
#  job:
#    admin:
#      addresses: http://xxljob:8080/xxl-job-admin
#    executor:
#      appname: ${spring.application.name}
#      ip:
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#    enabled: true

logging:
  level:
    com.microservice.oil: info
    org.springframework.cloud.openfeign: warn
    com.baomidou.mybatisplus: warn
    root: warn
  file:
    path: /data/logs/oil
    name: ${logging.file.path}/oil-prod.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 10GB

management:
  endpoints:
    web:
      exposure:
        include: "health,info" 