
server:
  port: 8083 # 发票管理服务端口
  servlet:
    context-path: /invoice

# API前缀配置
api:
  prefix: /api

spring:
  profiles:
    active: dev
  application:
    name: microservice-invoice
  
  # Jackson时区配置 - 设置为东八区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.microservice.invoice.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# nacos:
#   discovery:
#     server-addr: 127.0.0.1:8848
#   config:
#     server-addr: 127.0.0.1:8848

# seata:
#   enabled: true
#   tx-service-group: invoice-service-group

# sentinel:
#   transport:
#     dashboard: 127.0.0.1:8858